name: Production workflow

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
          with:
            node-version: 16.x
            cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build --if-present

      - name: Deploy to netlify
        uses: nwtgck/actions-netlify@v1.2
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          production-deploy: true
          production-branch: main
          publish-dir: "./dist"
          github-token: ${{secrets.GITHUB_TOKEN}}
          deploy-message: "Deploy from Github Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
